# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: generate_tunnel_interfaces_with_loops
# label used for menu selection
label: Create large output of repetitive set commands
description: show the use of jinja loops to crank out lots of set commands
type: template

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - test

# ---------------------------------------------------------------------
# end of preamble section

# variables section
variables:

  - name: interface_list
    description: loop list
    default:
      - 1
      - 5
      - 10
      - 100
      - 600

    type_hint: list

# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
snippets:

  - name: set_commands
    file: set_commands.conf

# ---------------------------------------------------------------------
# end of snippets section